[tools]
go = "1.26.3"
bun = "1.3.14"
"aqua:apple/pkl" = "0.31.1"
"aqua:moonrepo/moon" = "2.2.5"
"aqua:jdx/hk" = "1.45.0"
"aqua:golangci/golangci-lint" = "2.12.2"
"aqua:mvdan/gofumpt" = "0.10.0"
"aqua:rhysd/actionlint" = "1.7.12"
"aqua:zizmorcore/zizmor" = "1.25.2"
"go:golang.org/x/vuln/cmd/govulncheck" = "1.3.0"
"go:github.com/google/osv-scanner/v2/cmd/osv-scanner" = "2.3.8"
"aqua:gitleaks/gitleaks" = "8.30.1"

[env]
HK_MISE = "1"
